name = "oasis"
type = "javascript"
account_id = "96bea87fe68d650f41deb5e2883bce89"
zone_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-10-08"

kv_namespaces = [ 
    { binding = "KV_USERS", id = "4ab7d3d834c84e55ad3c7f56d1a3888a", preview_id = "4ab7d3d834c84e55ad3c7f56d1a3888a" },
    { binding = "KV_SESSIONS", id = "18c69cc125c64626a0602da2a711ca36", preview_id = "18c69cc125c64626a0602da2a711ca36" },
    { binding = "KV_SCHEMAS", id = "5c95d17eea3345da8438497a83ee353e", preview_id = "5c95d17eea3345da8438497a83ee353e" }
]

[vars]
GITHUB_CLIENT_ID = "daff23044c41eac40b68"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[site]
bucket = "./public" # Add the directory with your static assets!
entry-point = "." # JS folder serving your assets
